# --------- EVENT INPUT FEEDS BEGIN CONFIG ---------
agentHostedEventFeeds:
  - name: tradeEventFeed
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: /app/var/data_in/trades.jsonl
#      readStrategy: EARLIEST
      batchSize: 10
    valueMapper: !!com.telamin.app.pnl.TradeDtoDeserialiser { }
    wrapWithNamedEvent: false
    agentGroup: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }

  - name: symbolFeed
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: /app/var/data_in/symbols.jsonl
      publishOnStart: true
      readStrategy: EARLIEST
      batchSize: 5
    valueMapper: !!com.telamin.app.pnl.SymbolDtoDeserialiser { }
    wrapWithNamedEvent: false
    agentGroup: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }

  - name: rateFeed
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: /app/var/data_in/rates.jsonl
#      publishOnStart: true
      readStrategy: EARLIEST
      batchSize: 5
    valueMapper: !!com.telamin.app.pnl.MidPriceDtoDeserialiser { }
    wrapWithNamedEvent: false
    agentGroup: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }

  - name: positionSnapshot
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: /app/var/data_in/positionSnapshot.jsonl
      readStrategy: ONCE_LATEST
      publishOnStart: true
    valueMapper: !!com.telamin.app.pnl.PositionMapDeserialiser { }
    wrapWithNamedEvent: false
    agentGroup: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }
# --------- EVENT INPUT FEEDS END CONFIG ---------


# --------- EVENT OUTPUT SINK BEGIN CONFIG ---------
eventSinks:
  - name: globalNetMtmListener
    valueMapper: !!com.telamin.app.pnl.MapFunction$MapToJson { }
    instance: !!com.fluxtion.server.plugin.connector.file.FileMessageSink
      filename: /app/var/results/netMtm.jsonl
  - name: instrumentNetMtmListener
    valueMapper: !!com.telamin.app.pnl.MapFunction$MapToJson { }
    instance: !!com.fluxtion.server.plugin.connector.file.FileMessageSink
      filename: /app/var/results/instrumentMtm.jsonl
  - name: positionSnapshotListener
    valueMapper: !!com.telamin.app.pnl.MapFunction$MapToJson { }
    instance: !!com.fluxtion.server.plugin.connector.file.FileMessageSink
      filename: /app/var/data_in/positionSnapshot.jsonl
# --------- EVENT OUTPUT SINK END CONFIG ---------


# --------- EVENT HANDLERS BEGIN CONFIG ---------
eventHandlerAgents:
  - agentName: pnlCalulator-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }
    eventHandlers:
      pnlCalc:
        eventHandler: !!com.fluxtion.server.lib.pnl.calculator.FluxtionPnlCalculator { }
        logLevel: INFO
# --------- EVENT HANDLERS END CONFIG ---------