# --------- EVENT INPUT FEEDS BEGIN CONFIG ---------
eventFeeds:
  - name: tradeEventFeed
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: data_in/trades.jsonl
#      readStrategy: EARLIEST
    valueMapper: !!com.telamin.app.pnl.TradeDtoDeserialiser { }
    wrapWithNamedEvent: false
    agentName: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }

  - name: symbolFeed
#    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: data_in/symbols.jsonl
      cacheEventLog: true
      readStrategy: EARLIEST
    valueMapper: !!com.telamin.app.pnl.SymbolDtoDeserialiser { }
    wrapWithNamedEvent: true
    agentName: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }

  - name: rateFeed
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: data_in/rates.jsonl
      cacheEventLog: true
      readStrategy: EARLIEST
    valueMapper: !!com.telamin.app.pnl.MidPriceDtoDeserialiser { }
    wrapWithNamedEvent: false
    agentName: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }

  - name: positionSnapshot
    broadcast: true
    instance: !!com.fluxtion.server.plugin.connector.file.FileEventSource
      filename: data_in/positionSnapshot.jsonl
      readStrategy: ONCE_LATEST
      cacheEventLog: true
    valueMapper: !!com.telamin.app.pnl.PositionMapDeserialiser { }
    wrapWithNamedEvent: false
    agentName: fileReader-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }
# --------- EVENT INPUT FEEDS END CONFIG ---------


# --------- EVENT OUTPUT SINK BEGIN CONFIG ---------
eventSinks:
  - name: globalNetMtmListener
    valueMapper: !!com.telamin.app.pnl.MapFunction$MapToJson { }
    instance: !!com.fluxtion.server.plugin.connector.file.FileMessageSink
      filename: results/netMtm.jsonl
  - name: instrumentNetMtmListener
    valueMapper: !!com.telamin.app.pnl.MapFunction$MapToJson { }
    instance: !!com.fluxtion.server.plugin.connector.file.FileMessageSink
      filename: results/instrumentMtm.jsonl
  - name: positionSnapshotListener
    valueMapper: !!com.telamin.app.pnl.MapFunction$MapToJson { }
    instance: !!com.fluxtion.server.plugin.connector.file.FileMessageSink
      filename: data_in/positionSnapshot.jsonl
# --------- EVENT OUTPUT SINK END CONFIG ---------


# --------- SERVICE START CONFIG ---------
services:
  # Admin command registry
  - serviceClass:  com.fluxtion.server.service.admin.AdminCommandRegistry
    service: !!com.fluxtion.server.service.admin.impl.AdminCommandProcessor { }
  # Telnet admin
  - service: !!com.fluxtion.server.plugin.adminconsole.TelnetAdminCommandProcessor
      listenPort: 2099
  # Control fluxtion server
  - service: !!com.fluxtion.server.service.servercontrol.FluxtionServerAdmin { }
# --------- SERVICE END CONFIG ---------

# --------- EVENT HANDLERS BEGIN CONFIG ---------
eventHandlers:
  - agentName: pnlCalculator-thread
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy { }
    eventHandlers:
      pnlCalc:
        eventHandler: !!com.fluxtion.server.lib.pnl.calculator.FluxtionPnlCalculator { }
        logLevel: DEBUG
        configMap:
          errorLogName: errorLogger
# --------- EVENT HANDLERS END CONFIG ---------